<a href="https://colab.research.google.com/github/DanayaDiarra/MachineLearning/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00.Pytorch Fundamentals ##

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.8.0+cu126


## #Introduction to Tensors

### Creating Tensors (Using torch.tensor())

In [2]:
# Scaler

scaler = torch.tensor(7)
scaler

tensor(7)

In [3]:
scaler.ndim # A scaler has no dimension

0

In [4]:
# Get tensor back as python int
scaler.item()

7

In [5]:
# Vector
vector  = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.shape

torch.Size([2])

In [7]:
# MATRIX
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [8]:
MATRIX.ndim

2

In [9]:
MATRIX[1]

tensor([ 9, 10])

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                       [3,6,9],
                       [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [12]:
TENSOR.ndim

3

In [13]:
TENSOR.shape

torch.Size([1, 3, 3])

## Random Tensors

Why Random Tensors?

Random Tensors are important because the way neural networks learn is that they start with tensors full of random numbers and then adjust those to better represent the data.


*" start with random numbers -> look at data -> update random numbers -> look at data -> Update random numbers "*

### Torch random tensors.  https://docs.pytorch.org/docs/2.8/generated/torch.rand.html

In [14]:
# Create a random tensor of size(3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.8145, 0.8097, 0.3343, 0.2299],
        [0.3788, 0.6783, 0.2334, 0.2824],
        [0.1400, 0.8792, 0.4779, 0.4691]])

In [15]:
random_tensor.ndim

2

In [16]:
# Create a random tensor with a similar size to an image tensor
random_image_size_tensor = torch.rand(size=(3,224,224)) # height, width, colour channel
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

## #Creating Tensors with Zeros and Ones

In [17]:
# Create a Tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [18]:
# Create a tensor of all Ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [19]:
ones.dtype

torch.float32

## #Creating Tensors in a Range

In [20]:
# Use torch.range()
one_to_ten = torch.arange(start= 10, end= 100, step= 10)
one_to_ten

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [21]:
# Creating tensors like
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0])

###Dealing with Tensor Data types

In [22]:
# Float 32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype= None, # What datatype isi the tensor(float32 or float16)
                               device= None, # What device is the tensor on
                               requires_grad= False) #Wether or not to track gradients with this tensors operation
float_32_tensor

tensor([3., 6., 9.])

In [23]:
float_32_tensor.dtype

torch.float32

In [24]:
float_16_tensor =  float_32_tensor.type(torch.float16)
float_16_tensor


tensor([3., 6., 9.], dtype=torch.float16)

In [25]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

## #Getting attributes(information) from tensors

In [26]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.3138, 0.6199, 0.3253, 0.0752],
        [0.8909, 0.3089, 0.8703, 0.7732],
        [0.3089, 0.1709, 0.5610, 0.6472]])

In [27]:
# Find Out details about some tensor
print(some_tensor)
print(f'datatype of tensor:{some_tensor.dtype}')
print(f'shape of tensor: {some_tensor.shape}')
print(f'Device of tensor is: {some_tensor.device}')

tensor([[0.3138, 0.6199, 0.3253, 0.0752],
        [0.8909, 0.3089, 0.8703, 0.7732],
        [0.3089, 0.1709, 0.5610, 0.6472]])
datatype of tensor:torch.float32
shape of tensor: torch.Size([3, 4])
Device of tensor is: cpu


## #Manipulating Tensors (tensor operations)

Tensor Operations include:
 * Addition
 * Substration
 * Multiplication (element-wise)
 * Division
 * Matrix multiplication

In [28]:
# Create a tensor and add a number

tensor =  torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [29]:
torch.add(tensor, 10)

tensor([11, 12, 13])

In [30]:
# Multiply tensor

tensor * 10

tensor([10, 20, 30])

In [31]:
# Substract Tensor

tensor - 10

tensor([-9, -8, -7])

### #Matrix Multiplication
Two main ways of performing multiplication in Neural Networks and Deep Learning:



1.   Element-wise multiplication
2.   Matrix multiplication (dot product)


**Two(2) main rules multiplying tensors must satisfy**

1. The **Inner dimensions** must match
- *(2, 4) @ (2, 4)* won't work
- *(2, 4) @ (4, 2)* will work
- *(4, 2) @ (2, 4)* will work

2. The resulting Matrix has the shape of the **Outer dimensions**


In [32]:
# Element-wise multiplication
print(tensor, '*', tensor)
print(f'Equals:{tensor * tensor}')

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals:tensor([1, 4, 9])


In [33]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [34]:
# Matrix Multiplication manually
1*1 + 2*2 + 3*3

14

### #Dealing  with Tensor shape **errors**

In [35]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([
    [1,2],
    [3,4],
    [5,6]
])

tensor_B =  torch.tensor([
    [7, 10],
    [8, 11],
    [9, 12]
])

torch.matmul(tensor_A, tensor_B) # or torch.mm

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

#### Fixing the above issue using a **transpose** to manipulate the shape of one of the tensors.

a **transpose** switches the axes or dimensions of the given tensor

In [36]:
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [37]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [38]:
# The matrix multiplication works well when tensor_B is transposed

print(f'Original shape : Tensor_A = {tensor_A.shape}, Tensor_B = {tensor_B.shape}')
print(f'New shapes : Tensor_A = {tensor_A.shape}, Tensor_B = {tensor_B.T.shape}')
print(f'Multiplying :{tensor_A.shape} @ {tensor_B.T.shape} <- Inner dimension must match')
print('\n Output:')
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f'Output shape: {output.shape}')

Original shape : Tensor_A = torch.Size([3, 2]), Tensor_B = torch.Size([3, 2])
New shapes : Tensor_A = torch.Size([3, 2]), Tensor_B = torch.Size([2, 3])
Multiplying :torch.Size([3, 2]) @ torch.Size([2, 3]) <- Inner dimension must match

 Output:
tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])
Output shape: torch.Size([3, 3])


### Finding the Min, Max, Sum etc (Tensor aggregation)

In [39]:
# Create a tensor
x = torch.arange(0, 110, 10)
x, x.dtype

(tensor([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]), torch.int64)

In [40]:
# Find the min()
torch.min(x), x.min()

(tensor(0), tensor(0))

In [41]:
# Find the Max
torch.max(x), x.max()

(tensor(100), tensor(100))

In [42]:
# Find the Mean. NOTE: the 'torch.mean()' function requires `tensor of float32` dtype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()


(tensor(50.), tensor(50.))

In [43]:
# Find the Sum
torch.sum(x), x.sum()

(tensor(550), tensor(550))

### Finding the Positional min and max

In [44]:
x.shape

torch.Size([11])

In [45]:
# Find the position in tensor that has the minimum value with 'argmin()'
#->  Returtns the index position of the target tensor where the minimun value occurs
x.argmin()

tensor(0)

In [46]:
x[0]

tensor(0)

In [47]:
# Find the position in tensor that has the maximum value with 'argmax()'
x.argmax(), x[10]

(tensor(10), tensor(100))

### #Reshaping, Viewing, Stacking, Squeezing and unsquezing `tensors`

- **Reshaping** : reshape an input tensor to a defined shape
- **View**: Return a view of an input tensor of a cretain shape but keep the same memory as the original tensor
- **Stacking** : Combine multiple tensors on top of each other `"vstack"` or side by side `"hstack"`
- **Squeeze** : Remove all `1` dimensions from a tensor
- **Unsqueeze** : Add a `1` dimension to a target tensor
- **Permute** : Return a view of the input with dimension permuted(swapped) in a certaiin way


In [48]:
# Create a Tensor
import torch
x = torch.arange(1.,10.)
x , x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [49]:
# Add an Extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [50]:
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [51]:
# Changing `z` changes x (because a view of tensor shares the memory as the original)
z[:,0] = 1
z, x

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [52]:
# Stack tensorsbon top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [53]:
# Squeeze: remove all single dimensions from a target tensor
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [54]:
x_squeezed = x_reshaped.squeeze()
x_squeezed

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [55]:
x_squeezed.shape # 1 dimension removed

torch.Size([9])

In [56]:
# torch.unsqueeze(): adds a single dimension to a target tensor at a specific dim()
print(f'previous target : {x_squeezed}')
print(f'previous shape : {x_squeezed.shape}')

print('\n------------------------------------\n')

x_unsqueezed = x_squeezed.unsqueeze(dim=0)
# x_unsqueezed.shape
print(f'unsqueezed target : {x_unsqueezed}')
print(f'Current shape : {x_unsqueezed.shape}')

previous target : tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
previous shape : torch.Size([9])

------------------------------------

unsqueezed target : tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
Current shape : torch.Size([1, 9])


In [57]:
# torch.permute: Rearrange the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3)) # (height, width, colour_channels(RGB))

# Permute the Original tensor to arrange the axis or (dim) order

x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0
print(f'Original shape : {x_original.shape}')
print(f'New shape :      {x_permuted.shape}') # (Colour channels, height, width)

Original shape : torch.Size([224, 224, 3])
New shape :      torch.Size([3, 224, 224])


In [58]:
x_original

tensor([[[0.8754, 0.5005, 0.6515],
         [0.5471, 0.0817, 0.9762],
         [0.0356, 0.9684, 0.0490],
         ...,
         [0.7359, 0.3704, 0.5785],
         [0.8754, 0.7452, 0.0375],
         [0.4238, 0.1918, 0.4501]],

        [[0.4432, 0.9386, 0.6780],
         [0.1198, 0.2285, 0.1582],
         [0.1277, 0.1265, 0.7454],
         ...,
         [0.0764, 0.5678, 0.9323],
         [0.7433, 0.0101, 0.3957],
         [0.3492, 0.5137, 0.0449]],

        [[0.0994, 0.3824, 0.6602],
         [0.5332, 0.9711, 0.4276],
         [0.0409, 0.5087, 0.5058],
         ...,
         [0.3039, 0.6589, 0.8257],
         [0.7619, 0.1400, 0.1551],
         [0.9361, 0.5786, 0.4978]],

        ...,

        [[0.6918, 0.8423, 0.4021],
         [0.4251, 0.5546, 0.2886],
         [0.4368, 0.0826, 0.4042],
         ...,
         [0.0567, 0.0835, 0.0458],
         [0.3040, 0.4999, 0.6798],
         [0.9978, 0.8559, 0.1870]],

        [[0.1376, 0.8204, 0.5365],
         [0.2404, 0.0249, 0.3503],
         [0.

### #Selecting Data from tensor (indexing:)
Indexing with `PyTorch` is similar to indexingg in `numpy`

In [59]:
# Create a tensor
import torch
x = torch.arange(1, 26).reshape(1,5,5)
x, x.shape

(tensor([[[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10],
          [11, 12, 13, 14, 15],
          [16, 17, 18, 19, 20],
          [21, 22, 23, 24, 25]]]),
 torch.Size([1, 5, 5]))

In [60]:
# Indexing on our tensor
x[0]

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25]])

In [61]:
x[0][1]

tensor([ 6,  7,  8,  9, 10])

In [62]:
x[0][1][0]

tensor(6)

In [63]:
# Index on 'x' to return the last tensor_coloumn
x[:,:,-1]


tensor([[ 5, 10, 15, 20, 25]])

In [64]:
# Index on 'x' to return 25
x[0][4][4]

tensor(25)

## `PyTorch Tensors` and `Numpy`
- Data in NumPy -> PyTorch tensor for DeepL => `torch.from_numpy(ndarray)`
- PyTorch tensort to NumPy => `torch.tensor.numpy()`





In [76]:
from os import DirEntry
# NumPy array to tensor
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # PyTorch reflets NumPy's dtype as "float64" # Change the dtype to 'float32' if issues are encountered
tensor = tensor.type(dtype= torch.float32) # If needed !
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [77]:
array.dtype

dtype('float64')

In [78]:
tensor.dtype

torch.float32

In [79]:
# Change on the 'array' won't necessarly affect the 'tensor'
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [82]:
# Tensor to NumPy array
tensor = torch.ones(10)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [84]:
# Change on the 'tensor' won't directly affect the 'array' # They don't share memory
tensor = tensor + 1

tensor, numpy_tensor

(tensor([3., 3., 3., 3., 3., 3., 3., 3., 3., 3.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### #PyTorch reproducibility (taking the random out random)

In Short how a `neural network ` learns:

- `Start with random numbers -> perform tensor operations -> update random numbers and make them better representations of the data -> again and -> again`

- To reduce the  randomness in `neural networks` and `PyTorch` comes the concept of **`random seed`**

Essentially the 'random seed' `flavour` the randomness (The `seed` sets the specific starting point of the RNG(random number generator), which in turn defines the particular sequence of random numbers you will get).

In [90]:
# Create 2 random tensors to experiment the randomness of their values
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)
print(random_tensor_A)
print('---------------------------')
print(random_tensor_B)
print('---------------------------')
print(random_tensor_A == random_tensor_B)

tensor([[0.6452, 0.3667, 0.1260, 0.4295],
        [0.7050, 0.1724, 0.3415, 0.6610],
        [0.3866, 0.6037, 0.4378, 0.7131]])
---------------------------
tensor([[0.2199, 0.0346, 0.2652, 0.5623],
        [0.6401, 0.9059, 0.3274, 0.6141],
        [0.0915, 0.9987, 0.1540, 0.4824]])
---------------------------
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [95]:
# Some random but reproducible tensors

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED) # Work only for the 1st block of code

random_tensor_C = torch.rand(3, 4)

# torch.manual_seed(RANDOM_SEED) # If the we want the result to be identical
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print('---------------------')
print(random_tensor_D)
print('---------------------')
print(random_tensor_C == random_tensor_D)


tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
---------------------
tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])
---------------------
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])
